version: '3.8'

services:
  db:
    image: 'postgres:14.11'
    container_name: db
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5


  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - '7474:7474'   # Port HTTP pour Neo4j Browser
      - '7687:7687'   # Port Bolt pour la connexion à la base de données
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_dbms_default__database=${NEO4J_DATABASE}

    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
      neo4j:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_NEO4J_URI=${NEO4J_URL}
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=${NEO4J_USERNAME}
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=${NEO4J_PASSWORD}
      - SPRING_NEO4J_DATABASE=${NEO4J_DATABASE}

      - GOOGLE_APPLICATION_CREDENTIALS=configFirebase.json
volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: